### PR TITLE
add notification_created event to register on logs

### PR DESCRIPTION
**Pull request by danielneis**
Hello,
I've added this basic log just to check if you like the idea.
I'll add logs to update and delete too and more info on the log object (during this week).
Best,
Daniel

### CODE REVIEW

**Comment by danielneis** [comment]
Hi,
I've added log events for updating and deleting notifications.
Hope you like it.
Best,
Daniel

**Comment by zpottie** [comment]
Really like this too @danielneis - thanks! I'll give a proper look on my computer. 👌

**Review by zpottie — CHANGES_REQUESTED** [review]
The comment is for all crud logs' strings.

**Comment by danielneis** [comment]
Hi,
I would like it very much to see those strings translated, but all the log event descriptions are not translatable, they are all hardcoded.
https://tracker.moodle.org/browse/MDL-60565

**Comment by zpottie** [comment]
> Hi, I would like it very much to see those strings translated, but all the log event descriptions are not translatable, they are all hardcoded. https://tracker.moodle.org/browse/MDL-60565

Crazy, didn't even know that - all good then! Thanks for this! 👍

**Review by zpottie — APPROVED** [review]

**Pull request merged**
